
version: '3'

services:

    proj:
        container_name: ${BW_PROJ_NAME}-flask
        # image: tiangolo/meinheld-gunicorn-flask:python3.8
        image: bazawinner/dev-recommend-flask:${BW_DEV_FLASK_VERSION}
        # working_dir: /app/app
        tty: true
        environment:
            - TZ=Europe/Moscow

            - BW_PROJ_NAME
        ports:
            - $BW_DEV_FLASK_PORT:5000
        volumes:
            - ./src/flask:/app
